version: '3.9'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    ports:
      - "3000:143" # Map port 3000 of the container to the host
    networks:
      - app_network
    environment:
      DB_HOST: ${SQL_NAME}
      DB_USER: ${MSSQL_NAME}
      DB_PASSWORD: ${MSSQL_PASSWORD}
      DB_NAME: ${MSSQL_DATABASE}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - node-app
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
