version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    ports:
      - "3000:143" # Map port 3000 of the container to the host
    depends_on:
      - sql-server
    networks:
      - app_network
    environment:
      DB_HOST: ${SQL_NAME}
      DB_USER: ${MSSQL_NAME}
      DB_PASSWORD: ${MSSQL_PASSWORD}
      DB_NAME: ${MSSQL_DATABASE}

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${SQL_NAME}
    restart: always
    platform: "linux/amd64"
    networks:
      - app_network
    ports:
      - "1433:1433" # Expose SQL Server on default port
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      SA_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    volumes:
      - sqlserver_data:/var/opt/mssql

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - node-app
      - sql-server
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  sqlserver_data: