services:
  - type: web
    name: node-app
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free # Adjust the plan as per your requirements
    envVars:
      - key: DB_HOST
        value: "${SQL_NAME}" # Use the environment group for managing shared values
      - key: DB_USER
        value: "${MSSQL_NAME}"
      - key: DB_PASSWORD
        value: "${MSSQL_PASSWORD}"
      - key: DB_NAME
        value: "${MSSQL_DATABASE}"
    healthCheckPath: "/"
    autoDeploy: true
    regions:
      - oregon # Replace with your desired Render region
    port: 3000 # Ensure this matches your app's listening port

  - type: private_service
    name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    plan: free # Adjust as needed
    envVars:
      - key: ACCEPT_EULA
        value: "Y"
      - key: SA_PASSWORD
        value: "${MSSQL_PASSWORD}"
      - key: MSSQL_PID
        value: "${MSSQL_PID}"
